apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - serviceaccount.yml

images:
  - name: ghcr.io/meysam81/test-argocd-image-updater
    newTag: latest

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: test-argocd-image-updater
      app.kubernetes.io/instance: test-argocd-image-updater
      app.kubernetes.io/managed-by: Kustomize
      app.kubernetes.io/name: test-argocd-image-updater
      app.kubernetes.io/part-of: test-argocd-image-updater
      app.kubernetes.io/version: v1.0.0

namespace: default
