name: ci

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  build-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on the PR
        uses: meysam81/preview-bot@main
        with:
          url: https://pr{{.PR_NUMBER}}.example.com
          url-is-template: true
